### ISSUE TITLE
[FEATURE] Do we have any apis for mircosoft todo app ?

### ISSUE THREAD

**Issue by RahulSoni0** [microsoft/android-samples#5]
## 💡 Describe the feature

i need to integrate all the todos from microsoft todo within my new project , so i will need api references for the same

## 🙋‍♀️ Do you want to build the feature?

- [ ] Yes
- [ ] No

**Comment by parkerschroeder** [comment]
Hi RahulSoni0!

Microsoft does support To Do APIs, they are under a larger group of APIs called Microsoft Graph APIs. An overview on the To Do Graph APIs can be found here - https://learn.microsoft.com/graph/todo-concept-overview

If you're new to using Graph APIs in Android, consider browsing our recent blog series on how to get started 🙂.

 * [Using the Graph Explorer to easily test Graph APIs](https://devblogs.microsoft.com/surface-duo/microsoft-graph-android/)
 * [Authenticating Microsoft users in your app using MSAL](https://devblogs.microsoft.com/surface-duo/android-msal/)
 * [Calling Microsoft Graph APIs in an Android app](https://devblogs.microsoft.com/surface-duo/microsoft-graph-android-2/)
 * [Putting all the pieces together into a sample app](https://devblogs.microsoft.com/surface-duo/microsoft-graph-android-3/)

The third blog post covers different libraries you can use to call the Graph, but assuming you use the [GraphSDK for Java](https://github.com/microsoftgraph/msgraph-sdk-java), a simplified version of the code for getting all the task lists would look something like
```java
graphClient.me().todo().lists()
```
Hope this helps, best of luck with your app!

-Parker

**Comment by RahulSoni0** [comment]
@parkerschroeder Thank you so much
